### ISSUE TITLE
Measure with complex join query

### ISSUE THREAD

**Issue by wtholt** [tombenner/reports_kit#10]
First off, this is a great project. I was happy to see it in Ruby Weekly last week.

We're currently experimenting with incorporating the gem to use for a Reporting platform, generating reports on a database by a third party.

However, the data setup isn't as straightforward as some of the examples in the docs. We're having to do queries with nested joins. 

    class LogElement < ApplicationRecord
      self.table_name = "st_log_elements"
      belongs_to :event_log, foreign_key: "st_event_log_id"
      has_many :log_items, foreign_key: "st_log_element_id"

      def self.scenario_debriefing
        left_outer_joins(log_items: [[feedbacks: :arguments], :comments]).select("st_log_elements.*, 
        st_log_item_comments.comment_type as comment_type, st_log_item_comments.message_text 
        as message_text, st_log_item_instructor_feedbacks.feedback_text as feedback_text, 
        st_log_item_arguments.value as value").where(st_log_items: { type: ['InstructorFeedback', 
        'Comment'] }).order(:when_msec)
      end
    end

So far, we can show this data in a table by iterating over the records, but we'd ideally like to harness the cool features in your gem. 

Is it possible for ReportsKit to accept models with scopes on them?

So something like this potentially

     measure: log_element.scenario_debriefing
     dimensions:
        - when_msec
     format: table

Thanks again for this project, I think it will be extremely beneficial to the Ruby community.

**Comment by tombenner** [comment]
Yes, it's possible to use any sort of arbitrary filtering (including scopes) by using a custom boolean filter, as described in "Custom Filter" [here](https://www.reportskit.co/subcategories/filters).

For your use case, this would look like:

```ruby
class LogElement < ApplicationRecord
  self.table_name = "st_log_elements"
  belongs_to :event_log, foreign_key: "st_event_log_id"
  has_many :log_items, foreign_key: "st_log_element_id"

  def self.scenario_debriefing
    left_outer_joins(log_items: [[feedbacks: :arguments], :comments]).select("st_log_elements.*, 
    st_log_item_comments.comment_type as comment_type, st_log_item_comments.message_text 
    as message_text, st_log_item_instructor_feedbacks.feedback_text as feedback_text, 
    st_log_item_arguments.value as value").where(st_log_items: { type: ['InstructorFeedback', 
    'Comment'] }).order(:when_msec)
  end

  include ReportsKit::Model
  reports_kit do
    filter :scenario_debriefing, :boolean, conditions: ->(relation) { relation.scenario_debriefing }
  end
end
```

```yaml
measure: log_element
filters:
- key: scenario_debriefing
  criteria:
    value: true
dimensions:
  - when_msec
format: table
```

This should work for you, but it isn't as intuitive as it could be. We're discussing how to make the use of scopes more obvious and easier to use in #8. If you have any thoughts on that, more perspectives would certainly be helpful.

**Comment by wtholt** [comment]
Cheers! Works beautifully. 

Thanks for your quick response.

**Comment by kirantpatil** [comment]
Hi @tombenner  and @wtholt,

Reporting is not yet matured in Rails, I would like to call upon community members to come up with a shared knowledge base(wiki) for complex solutions which are not straight forward. 

Thanks.
