### ISSUE TITLE
Donut chart?

### ISSUE THREAD

**Issue by patricklindsay** [tombenner/reports_kit#11]
Hey, 

Gem looks good! Any plans for a [donut chart](https://datavizcatalogue.com/methods/donut_chart.html)?

**Comment by nsoseka** [comment]
HI
Report_skits using chart.js, and it comes with doughnut chart already. Consider adding this to the bottom of  report.yml file
```ruby 
chart:
  type: doughnut
  options:
    legend:
      display: true
      position: right
```
