### ISSUE TITLE
date is not displaying correctly 

### ISSUE THREAD

**Issue by smitakiran25** [tombenner/reports_kit#27]
3rd jan 2018 i have created 3 subscribers, but in report the created_at date is displaying as dec 31st 17 
![screenshot from 2018-01-03 17-45-54](https://user-images.githubusercontent.com/11611902/34520275-106ff408-f0ae-11e7-87e6-6640f6136e86.png)

please tell me how to resolve this issue
thank you

**Comment by tombenner** [comment]
By default, datetime dimensions are grouped by week ([here](https://www.reportskit.co/examples/dimension_datetime)'s an example), with the week starting [on Sunday](https://www.reportskit.co/subcategories/first_day_of_the_week). In the screenshot above, Dec 31, '17 is a Sunday and represents the week of Dec 31, during which the subscribers were created.

We'll want to document this in [reports_kit_docs](https://github.com/tombenner/reports_kit_docs), but until then, there are tests that show how to change the granularity (e.g. `day`, `week`, or `month`) of a datetime dimension [here](https://github.com/tombenner/reports_kit/blob/master/spec/reports_kit/reports/data/generate_spec.rb#L247-L307). For example, that first test indicates that you can set the granularity of a datetime dimension to be `day` like this (see the `properties` definition in the test):

```yaml
measure: subscriber
dimensions:
- key: created_at
  granularity: day
```
