### ISSUE TITLE
Multi-Autocomplete filter showing ID not names

### ISSUE THREAD

**Issue by billy-whizz** [tombenner/reports_kit#53]
I have been able to successfully create a multi-autocomplete filter for my chart. However, instead of showing the association model's names in the dropdown, it is showing  the model IDs. In my case, an author has_many posts. So in my chart, instead of seeing the author names in the filter, I see something like  #<Author:0X0007f2c85fc83f8>

**Comment by nsoseka** [comment]
Hi
Go to the author model and override the to_s method in the model to this
```ruby
def to_s
  authors_name
end
``` 
remember to replace authors_name method here with the attribute column that returns the authors name in your model.

**Comment by billy-whizz** [comment]
Thank you, this solves the issue.
