### ISSUE TITLE
Adding scopes to measures, filters and dimensions

### ISSUE THREAD

**Issue by jasonpaluck** [tombenner/reports_kit#7]
Firstly, thanks for all your work on an excellent project! 

I need to add scopes (class methods) to the relations defined as measures, filters and dimensions such as `.for_organization(current_organization)`. I'm struggling to add scopes at all, let alone accessing helper methods such as `current_user` or `current_organization` that would normally be available to controller contexts. The filter initializer context doesn't have access to those methods either.

Any thoughts?

**Comment by tombenner** [comment]
This can be done using a [Context Record](https://www.reportskit.co/subcategories/context_record). Here's an example using `current_user`:

```ruby
class User < ApplicationRecord
  has_many :posts
end
```

```haml
= render_report 'my_posts', context_params: { foo: 'bar' }
```

```yaml
measure: post
dimensions:
- is_published
```

```ruby
# config/initializers/reports_kit.rb

ReportsKit.configure do |config|
  config.context_record_method = lambda do |controller|
    context_params = controller.params[:context_params]
    # You could use any other context_params-related conditional here, or even omit this line if all of your reports are scoped to `current_user`
    return nil unless context_params && context_params[:foo] == 'bar'
    current_user
  end
end
```

If `context_record_method` returns nil, then the query that's run is effectively `Post.group(:is_published).count`.

If `context_record_method` returns a `User` instance (via `current_user`), then the query that's run is effectively `current_user.posts.group(:is_published).count`.

Does this solve your use case?

---

### Other Thoughts

This Context Record-based solution (described above) isn't as intuitive as I'd like.

One approach that I've been considering is having a "contextual_filter" (there may be a better name for this) that works like so:

```yaml
measure: post
contextual_filter: my_contextual_filter
dimensions:
- is_published
```

```ruby
class User < ApplicationRecord
  has_many :posts

  include ReportsKit::Model
  reports_kit do
    contextual_filter :my_contextual_filter, ->(relation, controller) { relation.where(user_id: controller.current_user.id) }
  end
end
```

This would 1) be fairly flexible and applicable to many use cases, and 2) move the filtering out of `config/initializers/reports_kit.rb` and into the report YAML and model, where the other filtering is done. If we used this, we would likely deprecate the Context Record approach.

Would this solution be more intuitive to you, and would it solve your use case?

Are there other solutions that would be better than this?

**Comment by jasonpaluck** [comment]
Thanks for the detailed response! After thinking about this for a few days, my sense is the contextual filter solution would be far more intuitive and flexible. I tend to not lean on chained relationships (`current_user.posts`) and instead opt to write class methods that yield more clarity around the final object to be returned (`Post.for_user(current_user)`). The first method you propose would require a good amount of refactoring for me, and while I'm happy to do that for the opportunity to use your project, I suspect others will find the current context record implementation a bit confusing as I did.

I'll try out the currently available solution now and circle back if I run into any roadblocks.

Thanks!

**Comment by tombenner** [comment]
Great, thanks for giving this some thought. This feedback is very helpful, and everything you mentioned is very much in line with my perspective, too. This improvement will (hopefully) not only reduce confusion, but also allow us to remove the Context Record-related code, which would simplify ReportsKit's implementation significantly.

To see what this new solution would look like, I've done a very rough implementation of it, and it looks relatively straightforward. It's already working well to replace Context Records in a large app that makes somewhat heavy use of Context Records.

If you or anyone else wants to keep up with it, I have an initial implementation of it in [this branch](https://github.com/tombenner/reports_kit/compare/contextual_filters?expand=1), but it's very much a work in progress without documentation yet. When it's in a more stable state, I'll mention it here again, and if you want to, you could try it out then to see if it meets your needs. (Or if you prefer, you can just wait til it's in a stable release :) ).

**Comment by jasonpaluck** [comment]
Thanks! I'll check out the branch and let you know if I see any issues with the new direction.

**Comment by tombenner** [comment]
There has been a decent amount of confusion about context records, and ReportsKit is nascent enough that it's still possible to iterate quickly on it without impacting too many users, so I've gone ahead and added contextual filters in 0.4.0. They're additive, so no existing functionality will break, but newcomers will more easily know that they exist and be able to try them out.

Contextual filters are documented [here](https://www.reportskit.co/subcategories/contextual_filters). I've deprecated context records in both this library and in the documentation.

They've been working well in a Rails app that has historically made fairly heavy use of ReportsKit and context records, so they seem to fit at least that use case, but additional feedback would definitely still be helpful.

**Comment by jasonpaluck** [comment]
This is working well for appending scopes to measures, thanks! Next question is filters. If I've got a filter key for `user` I'm still getting all users in the filter select as `User.all` but I need to append `User.for_organization(current_organization)`. I'm not seeing how to add any context to the filter since the custom filter is meant to only be a relation scope on the measure object. Is there any way to append that context to a filter?

**Comment by tombenner** [comment]
Just to clarify, do you mean that you have a [multi-autocomplete filter](https://www.reportskit.co/examples/interaction_filter_multi_autocomplete) for a `user` association, and you're seeing that the results in that autocomplete are all users (`User.all`)?

If so, then the current way to scope the results to the organization is to use the [autocomplete_results_method](https://www.reportskit.co/subcategories/autocomplete) to modify the autocomplete's results. Your implementation might look something like this:

```
# config/initializers/reports_kit.rb

ReportsKit.configure do |config|
  config.autocomplete_results_method = lambda do |params:, context_record:, relation:|
    query = params[:q]
    relation = relation.for_organization(params[:context_params][:organization_id])
    results = relation.where('name ILIKE ?', "%#{query}%").order('name').limit(30)
    results.map do |result|
      {
        id: result.id,
        text: "#{result.last_name}, #{result.first_name}" }
      }
    end
  end
end
```

As described in the context filter documentation, if you need to validate the `params[:context_params]` value, you can do so like [this](https://www.reportskit.co/subcategories/context_params_modification).

---

However, this is not an obvious nor easily-used solution. As you mentioned, it would probably make sense to configure this in the filter's configuration in the YAML. Would something like the following make sense to you? Or perhaps there's a better solution?

```yaml
measure: post
filters:
- key: user
  contextual_filters:
  - for_organization
dimensions:
- is_published
```

**Comment by jasonpaluck** [comment]
```
filters:
- key: user
  contextual_filters:
  - for_organization
```
Is exactly what I was hoping for, that would make it consistent with the measure contextual filter implementation. Thanks again for all your effort here!

**Comment by tombenner** [comment]
The use of `contextual_filters` within `filters` is now supported in 0.5.0. The documentation that more thoroughly explains this is [here](https://www.reportskit.co/examples/contextual_filters_in_multi_autocompletes).

I've also added documentation about [Multi-Autocomplete Results Filtering](https://www.reportskit.co/examples/interaction_filter_multi_autocomplete_filtering) that describes the two methods for achieving this.

I believe that the needs described in this issue should be supported now, so I'll close the issue. If there are other aspects to this, it might be best to open a new issue so that we can specifically focus on them. Thanks for surfacing these needs; I hope these are helpful additions!
